"use strict";
let car = 'subaru';
console.log("Is car === 'subaru'? I predict True.");
console.log(car === 'subaru');
console.log("Is car == 'subaru'? I predict True.");
console.log(car == 'subaru');
console.log("Is car != 'Honda'? I predict True.");
console.log(car != 'Honda');
console.log("Is car !== 'Mustang'? I predict True.");
console.log(car !== 'Mustang');
console.log("Is car.Upper case == 'SUBARU'? I predict True.");
console.log(car.toUpperCase() == 'SUBARU');
console.log("Is car == 'SUBARU'? I predict False.");
console.log(car == 'SUBARU');
console.log("Is car === 'SUBARU'? I predict False.");
console.log(car === 'SUBARU');
console.log("Is car === 'Train'? I predict False.");
console.log(car === 'Train');
console.log("Is car === 'Aero Plane'? I predict False.");
console.log(car === 'Aero Plane');
console.log("Is car === 'Bike'? I predict False.");
console.log(car === 'Bike');
