"use strict";
let places = ['Italy', 'Germany', 'Agra', 'Eifel Tower', 'Times Square'];
console.log('orignal' + places);
console.log('copy' + [...places].sort());
console.log('copy' + places);
console.log('copy' + [...places].sort().reverse());
console.log('orignal' + places);
console.log('orignal' + places.reverse());
console.log('orignal' + places.reverse());
console.log('orignal' + places.sort());
console.log('orignal' + places.sort().reverse());
